In [13]:
l1=[20,10,2,3,4]
l2=[1,10,12,5,3]
l3=[l1]+[l2]
print(l3)
print(l3[0][4])

[[20, 10, 2, 3, 4], [1, 10, 12, 5, 3]]
4


In [14]:
import numpy as np
l1=[1,2,3,4,5,6,7,8,9,10]
print(l1)
v1=np.array(l1)
print(v1)
print(v1[v1>5])
print(v1+5)
print(v1*5)
print(v1[1:5])
print(v1[::-1])
print(v1[0:5:-1])


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]
[ 5 10 15 20 25 30 35 40 45 50]
[2 3 4 5]
[10  9  8  7  6  5  4  3  2  1]
[]


In [18]:
import numpy as np
s=[[1,2,3,],[3,4,5],[5,6,7]]
s1=np.array(s)
print(s1[1])
print(s1[2])
print(s1[-1])
print(s1[1][1])
print(s1[1][-1])
print(s1[-1][-2])
print(s1[1][0])
s1[0][0]=12
s2=(s1+s1)
print(s2)
print([[s1],[s1]])

[3 4 5]
[5 6 7]
[5 6 7]
4
5
6
3
[[24  4  6]
 [ 6  8 10]
 [10 12 14]]
[[array([[12,  2,  3],
       [ 3,  4,  5],
       [ 5,  6,  7]])], [array([[12,  2,  3],
       [ 3,  4,  5],
       [ 5,  6,  7]])]]
